using System.CodeDom.Compiler;
using HKW.SourceGeneratorUtils;
using Microsoft.CodeAnalysis;

namespace HKW.MVVM.SourceGenerator;

internal sealed class ChangeArgsCache
{
    public ChangeArgsCache(Compilation compilation)
    {
        var assemblyName = compilation.AssemblyName!.Replace(".", "_");
        ChangingName = $"{assemblyName}_PropertyChangingArgsCache";
        ChangedName = $"{assemblyName}_PropertyChangedArgsCache";
    }

    public string ChangingName { get; }
    public string ChangedName { get; }
    public Dictionary<string, PropertyGenerateInfo> ChangingArgs { get; } = [];
    public Dictionary<string, PropertyGenerateInfo> ChangedArgs { get; } = [];

    public const string Namespace = "HKW.MVVM.SourceGenerator";

    public string GetChangingArgs(string propertyName)
    {
        if (ChangingArgs.TryGetValue(propertyName, out var property) is false)
        {
            property = ChangingArgs[propertyName] = new(
                MVVMGenerator.PropertyChangingEventArgs,
                propertyName,
                new()
            )
            {
                IsStatic = true,
                Default = $"new(\"{propertyName}\")",
                Accessibility = Accessibility.Public,
            };
        }
        return $"{GeneratorHelper.GlobalPrefix}{Namespace}.{ChangingName}.{property.Name}";
    }

    public string GetChangedArgs(string propertyName)
    {
        if (ChangedArgs.TryGetValue(propertyName, out var property) is false)
        {
            property = ChangedArgs[propertyName] = new(
                MVVMGenerator.PropertyChangedEventArgs,
                propertyName,
                new()
            )
            {
                IsStatic = true,
                Default = $"new(\"{propertyName}\")",
                Accessibility = Accessibility.Public,
            };
        }
        return $"{GeneratorHelper.GlobalPrefix}{Namespace}.{ChangedName}.{property.Name}";
    }

    public void WriteTo(SourceProductionContext productionContext)
    {
        var stringStream = new StringWriter();
        var writer = new IndentedTextWriter(stringStream);
        writer.WriteLine("// <auto-generated>");
        writer.WriteLine($"namespace {ChangeArgsCache.Namespace}");
        writer.WriteLine("{");
        writer.Indent++;

        writer.WriteLine($"internal static class {ChangingName}");
        writer.WriteLine("{");
        writer.Indent++;
        foreach (var property in ChangingArgs.Values)
            writer.WriteInfo(property);
        writer.Indent--;
        writer.WriteLine("}");

        writer.WriteLine($"internal static class {ChangedName}");
        writer.WriteLine("{");
        writer.Indent++;
        foreach (var property in ChangedArgs.Values)
            writer.WriteInfo(property);
        writer.Indent--;
        writer.WriteLine("}");

        writer.Indent--;
        writer.WriteLine("}");
        productionContext.AddSource(
            $"ChangeArgsCache.g.cs",
            ((StringWriter)writer.InnerWriter).ToString()
        );
    }
}
