using System.CodeDom.Compiler;
using System.Text;
using HKW.SourceGeneratorUtils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HKW.MVVM.SourceGenerator;

internal class ClassSourceWriter
{
    public static void Execute(ClassInfo classInfo)
    {
        var w = new ClassSourceWriter(classInfo);
        w.WriteObservableObject();
    }

    public static string FirstClassFullName { get; set; } = string.Empty;

    private readonly ClassInfo _classInfo;

    public ClassSourceWriter(ClassInfo classInfo)
    {
        _classInfo = classInfo;
    }

    private void WriteObservableObject()
    {
        var stringStream = new StringWriter();
        var writer = new IndentedTextWriter(stringStream);
        writer.WriteLine("// <auto-generated>");
        writer.WriteLine("#nullable enable");
        writer.WriteLine("#pragma warning disable CS1591");
        // 添加全部引用
        writer.WriteLine(_classInfo.Usings);
        // 添加命名空间
        writer.WriteLine($"namespace {_classInfo.Namespace}");
        writer.WriteLine("{");
        writer.Indent++;
        // 添加 ReferenceType 特性,并引用 HKW.MVVM.SourceGenerator
        // 防止编译器优化,如果整个项目中不引用 HKW.MVVM.SourceGenerator, 会导致程序集未被引用让 Fody 无法正常构建
        writer.WriteLine(
            "[global::HKW.MVVM.SourceGenerator.ReferenceType(typeof(global::HKW.MVVM.SourceGenerator.ReferenceTypeAttribute))]"
        );
        // 获取可访问性
        var accessibility = _classInfo.DeclarationSyntax.Modifiers.GetAccessibility();
        writer.WriteLine(
            $"{accessibility}{(_classInfo.ClassSymbol.IsAbstract ? " abstract" : string.Empty)} partial class {_classInfo.TypeName}"
        );
        // 添加约束列表
        if (_classInfo.DeclarationSyntax.ConstraintClauses.Count > 0)
            writer.WriteLine($"{_classInfo.DeclarationSyntax.ConstraintClauses}");
        writer.WriteLine("{");
        writer.Indent++;

        foreach (var info in _classInfo.Members)
            writer.WriteInfo(info);
        GenerateReactiveHelper(writer);

        writer.Indent--;
        writer.WriteLine();
        writer.WriteLine("}");
        writer.Indent--;
        writer.WriteLine("}");

        _classInfo.ProductionContext.AddSource(
            $"{_classInfo.FullTypeName.ReplaceBraces()}.g.cs",
            ((StringWriter)writer.InnerWriter).ToString()
        );
    }

    public void GenerateReactiveHelper(IndentedTextWriter writer)
    {
        writer.WriteLine();
        writer.WriteLine("/// <inheritdoc/>");
        writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);
        writer.WriteLine($"protected sealed partial class {_classInfo.HelperObjectName}");
        writer.WriteLine("{");
        writer.Indent++;
        GenerateReactiveHelperCtor(writer);
        writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);
        writer.WriteLine(GeneratorHelper.DebuggerBrowsableNeverAttribute);
        writer.WriteLine($"{_classInfo.FullTypeName} {ClassInfo.SourceName};");
        foreach (var info in _classInfo.HelperMembers)
            writer.WriteInfo(info);

        writer.Indent--;
        writer.WriteLine("}");
    }

    private void GenerateReactiveHelperCtor(IndentedTextWriter writer)
    {
        writer.WriteLine("/// <inheritdoc/>");
        writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);

        writer.WriteLine(
            $"public {_classInfo.HelperObjectName}({_classInfo.FullTypeName} {ClassInfo.SourceParamName})"
        );
        writer.WriteLine("{");
        writer.Indent++;
        writer.WriteLine($"{ClassInfo.SourceName} = {ClassInfo.SourceParamName};");

        foreach (var member in _classInfo.InitializeMembers)
        {
            writer.WriteLine(member);
        }

        writer.Indent--;
        writer.WriteLine("}");
    }
}
