using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace HKW.MVVM.SourceGenerator;

[Generator]
internal sealed class DIGenerator : IIncrementalGenerator
{
    private const string RegistrationsTypeName =
        "HKW.MVVM.SourceGenerator.DependencyInjectionRegistrations";
    private const string ConstructorAttributeName =
        "HKW.MVVM.SourceGenerator.DependencyInjectionConstructorAttribute";
    private const string PropertyAttributeName =
        "HKW.MVVM.SourceGenerator.DependencyInjectionPropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var registrations = context
            .SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax,
                static (syntaxContext, _) => GetRegistration(syntaxContext)
            )
            .Where(static registration => registration is not null)
            .Select(static (registration, _) => registration!)
            .Collect();

        context.RegisterSourceOutput(
            context.CompilationProvider.Combine(registrations),
            static (productionContext, input) =>
                Generate(productionContext, input.Left, input.Right)
        );
    }

    private static Registration? GetRegistration(GeneratorSyntaxContext context)
    {
        var invocation = (InvocationExpressionSyntax)context.Node;
        if (context.SemanticModel.GetSymbolInfo(invocation).Symbol is not IMethodSymbol method)
            return null;
        if (method.ContainingType.ToDisplayString() != RegistrationsTypeName)
            return null;
        if (method.TypeArguments.Length is < 1 or > 2)
            return null;

        var lifetime = method.Name switch
        {
            "Register" => ServiceLifetime.Transient,
            "RegisterScoped" => ServiceLifetime.Scoped,
            "RegisterSingleton" or "RegisterLazySingleton" => ServiceLifetime.Singleton,
            _ => ServiceLifetime.None,
        };
        if (lifetime == ServiceLifetime.None)
            return null;

        var serviceType = method.TypeArguments[0];
        var implementationType =
            method.TypeArguments.Length == 1 ? serviceType : method.TypeArguments[1];
        return new Registration(
            serviceType,
            implementationType,
            lifetime,
            invocation.GetLocation()
        );
    }

    private static void Generate(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<Registration> registrations
    )
    {
        var body = new StringBuilder();
        foreach (var registration in registrations)
        {
            if (!TryCreateFactory(context, compilation, registration, out var factory))
                continue;

            var method = registration.Lifetime switch
            {
                ServiceLifetime.Transient => "AddTransient",
                ServiceLifetime.Scoped => "AddScoped",
                _ => "AddSingleton",
            };
            body.Append(
                    "        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions."
                )
                .Append(method)
                .Append('<')
                .Append(Display(registration.ServiceType))
                .AppendLine(">(services, serviceProvider =>")
                .AppendLine("        {")
                .Append("            return ")
                .Append(factory)
                .AppendLine(";")
                .AppendLine("        });");
        }

        var source = $$"""
            // <auto-generated/>
            #nullable enable
            namespace HKW.MVVM.SourceGenerator
            {
                /// <summary>Applies dependency injection registrations declared in this assembly.</summary>
                public static class GeneratedServiceCollectionExtensions
                {
                    /// <summary>Adds all source-generated service registrations.</summary>
                    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedServices(
                        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
                    {
                        if (services is null)
                            throw new global::System.ArgumentNullException(nameof(services));
            {{body}}            return services;
                    }
                }
            }
            """;
        context.AddSource(
            "HKW.MVVM.DependencyInjection.g.cs",
            SourceText.From(source, Encoding.UTF8)
        );
    }

    private static bool TryCreateFactory(
        SourceProductionContext context,
        Compilation compilation,
        Registration registration,
        out string factory
    )
    {
        factory = string.Empty;
        if (
            registration.ImplementationType is not INamedTypeSymbol implementationType
            || implementationType.TypeKind != TypeKind.Class
            || implementationType.IsAbstract
            || implementationType.IsUnboundGenericType
        )
        {
            context.ReportDiagnostic(
                Diagnostic.Create(
                    DIDescriptors.InvalidImplementationType,
                    registration.Location,
                    Display(registration.ImplementationType)
                )
            );
            return false;
        }

        if (
            !compilation
                .ClassifyCommonConversion(implementationType, registration.ServiceType)
                .IsImplicit
        )
        {
            context.ReportDiagnostic(
                Diagnostic.Create(
                    DIDescriptors.IncompatibleServiceType,
                    registration.Location,
                    Display(implementationType),
                    Display(registration.ServiceType)
                )
            );
            return false;
        }

        var constructors = implementationType.InstanceConstructors;
        var markedConstructors = constructors
            .Where(static constructor => HasAttribute(constructor, ConstructorAttributeName))
            .ToImmutableArray();
        IMethodSymbol? constructor;
        if (constructors.Length == 1 && markedConstructors.Length <= 1)
            constructor = constructors[0];
        else if (markedConstructors.Length == 1)
            constructor = markedConstructors[0];
        else
        {
            context.ReportDiagnostic(
                Diagnostic.Create(
                    DIDescriptors.AmbiguousConstructor,
                    registration.Location,
                    Display(implementationType)
                )
            );
            return false;
        }

        if (!IsAccessible(constructor.DeclaredAccessibility))
        {
            context.ReportDiagnostic(
                Diagnostic.Create(
                    DIDescriptors.InaccessibleConstructor,
                    constructor.Locations.FirstOrDefault() ?? registration.Location,
                    Display(implementationType)
                )
            );
            return false;
        }

        var arguments = string.Join(
            ", ",
            constructor.Parameters.Select(parameter => Resolve(parameter.Type))
        );
        var properties = GetInjectedProperties(compilation, implementationType);
        foreach (var property in properties)
        {
            if (
                property.IsStatic
                || property.IsIndexer
                || property.SetMethod is null
                || !IsAccessible(property.SetMethod.DeclaredAccessibility)
            )
            {
                context.ReportDiagnostic(
                    Diagnostic.Create(
                        DIDescriptors.InvalidInjectedProperty,
                        property.Locations.FirstOrDefault() ?? registration.Location,
                        property.Name,
                        Display(implementationType)
                    )
                );
                return false;
            }
        }

        var builder = new StringBuilder()
            .Append("new ")
            .Append(Display(implementationType))
            .Append('(')
            .Append(arguments)
            .Append(')');
        if (properties.Count > 0)
        {
            builder.AppendLine().AppendLine("            {");
            foreach (var property in properties)
            {
                builder
                    .Append("                ")
                    .Append(EscapeIdentifier(property.Name))
                    .Append(" = ")
                    .Append(Resolve(property.Type))
                    .AppendLine(",");
            }
            builder.Append("            }");
        }
        factory = builder.ToString();
        return true;
    }

    private static List<IPropertySymbol> GetInjectedProperties(
        Compilation compilation,
        INamedTypeSymbol implementationType
    )
    {
        var properties = new List<IPropertySymbol>();
        for (var type = implementationType; type is not null; type = type.BaseType)
        {
            if (
                !SymbolEqualityComparer.Default.Equals(
                    type.ContainingAssembly,
                    compilation.Assembly
                )
            )
                break;
            properties.AddRange(
                type.GetMembers()
                    .OfType<IPropertySymbol>()
                    .Where(static property => HasAttribute(property, PropertyAttributeName))
            );
        }
        return properties;
    }

    private static string Resolve(ITypeSymbol type)
    {
        if (
            type is INamedTypeSymbol namedType
            && namedType.IsGenericType
            && namedType.TypeArguments.Length == 1
        )
        {
            var definition = namedType.OriginalDefinition.ToDisplayString();
            var argument = Display(namedType.TypeArguments[0]);
            if (definition == "System.Lazy<T>")
            {
                return $"new global::System.Lazy<{argument}>(() => global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{argument}>(serviceProvider))";
            }
            if (definition == "System.Collections.Generic.IEnumerable<T>")
            {
                return $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices<{argument}>(serviceProvider)";
            }
        }
        return $"global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{Display(type)}>(serviceProvider)";
    }

    private static bool HasAttribute(ISymbol symbol, string attributeName) =>
        symbol
            .GetAttributes()
            .Any(attribute => attribute.AttributeClass?.ToDisplayString() == attributeName);

    private static bool IsAccessible(Accessibility accessibility) =>
        accessibility
            is Accessibility.Public
                or Accessibility.Internal
                or Accessibility.ProtectedOrInternal;

    private static string Display(ITypeSymbol type) =>
        type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

    private static string EscapeIdentifier(string name) =>
        Microsoft.CodeAnalysis.CSharp.SyntaxFacts.GetKeywordKind(name)
        != Microsoft.CodeAnalysis.CSharp.SyntaxKind.None
            ? "@" + name
            : name;

    private enum ServiceLifetime
    {
        None,
        Transient,
        Scoped,
        Singleton,
    }

    private sealed class Registration(
        ITypeSymbol serviceType,
        ITypeSymbol implementationType,
        ServiceLifetime lifetime,
        Location location
    )
    {
        public ITypeSymbol ServiceType { get; } = serviceType;
        public ITypeSymbol ImplementationType { get; } = implementationType;
        public ServiceLifetime Lifetime { get; } = lifetime;
        public Location Location { get; } = location;
    }
}
