// <auto-generated/>
#nullable enable

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.ExceptionServices;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;

namespace HKW.MVVM.SourceGenerator
{
/// <summary>
/// 由依赖注入源生成器创建的轻量服务提供程序。
/// </summary>
public sealed class DIServiceProvider
    : IServiceProvider,
        IServiceScopeFactory,
        IServiceProviderIsService,
        IDisposable
#if HKW_DI_ASYNC_DISPOSABLE
        , IAsyncDisposable
#endif
{
    private static readonly AsyncLocal<ResolutionFrame?> _currentResolution =
        new AsyncLocal<ResolutionFrame?>();
    private readonly Dictionary<Type, Registration[]> _registrations =
        new Dictionary<Type, Registration[]>();
    private readonly Dictionary<Type, Func<ScopeState, object?>> _serviceAccessors =
        new Dictionary<Type, Func<ScopeState, object?>>();
    private readonly ConcurrentDictionary<Type, Func<ScopeState, object?>> _enumerableAccessors =
        new ConcurrentDictionary<Type, Func<ScopeState, object?>>();
    private readonly ServiceProviderOptions _options;
    private readonly ScopeState _rootScope;
    private int _disposed;

    /// <summary>
    /// 使用工厂型服务描述符初始化服务提供程序
    /// </summary>
    public DIServiceProvider(IEnumerable<ServiceDescriptor> serviceDescriptors)
        : this(
            serviceDescriptors,
            new ServiceProviderOptions(),
            Array.Empty<DIServiceRegistrationMetadata>()
        ) { }

    /// <summary>
    /// 使用工厂型服务描述符和验证选项初始化服务提供程序
    /// </summary>
    public DIServiceProvider(
        IEnumerable<ServiceDescriptor> serviceDescriptors,
        ServiceProviderOptions options
    )
        : this(serviceDescriptors, options, Array.Empty<DIServiceRegistrationMetadata>()) { }

    /// <summary>
    /// 使用工厂型服务描述符、验证选项和生成依赖元数据初始化服务提供程序
    /// </summary>
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
    public DIServiceProvider(
        IEnumerable<ServiceDescriptor> serviceDescriptors,
        ServiceProviderOptions options,
        IEnumerable<DIServiceRegistrationMetadata> metadata
    )
    {
        if (serviceDescriptors is null)
            throw new ArgumentNullException(nameof(serviceDescriptors));
        _options = options ?? throw new ArgumentNullException(nameof(options));
        if (metadata is null)
            throw new ArgumentNullException(nameof(metadata));

        var registrations = new Dictionary<Type, List<Registration>>();
        var id = 0;
        foreach (var descriptor in serviceDescriptors)
        {
            if (
                descriptor.IsKeyedService
                || descriptor.ImplementationFactory is null
                || descriptor.ServiceType.ContainsGenericParameters
            )
            {
                throw new InvalidOperationException(
                    $"Registration for '{descriptor.ServiceType}' must use a non-keyed factory method and a closed service type."
                );
            }

            if (registrations.TryGetValue(descriptor.ServiceType, out var services) is false)
            {
                services = new List<Registration>();
                registrations.Add(descriptor.ServiceType, services);
            }
            services.Add(
                new Registration(
                    id++,
                    descriptor.ServiceType,
                    descriptor.Lifetime,
                    descriptor.ImplementationFactory
                )
            );
        }

        foreach (var pair in registrations)
        {
            var serviceRegistrations = pair.Value.ToArray();
            _registrations.Add(pair.Key, serviceRegistrations);
            var lastRegistration = serviceRegistrations[serviceRegistrations.Length - 1];
            _serviceAccessors.Add(pair.Key, scope => ResolveRegistration(lastRegistration, scope));
        }
        _rootScope = new ScopeState(this, true);
        if (_options.ValidateOnBuild)
            ValidateOnBuild(metadata);
    }

    /// <inheritdoc />
    public object? GetService(Type serviceType)
    {
        if (serviceType is null)
            throw new ArgumentNullException(nameof(serviceType));
        return GetService(serviceType, _rootScope);
    }

    /// <summary>
    /// 创建服务作用域
    /// </summary>
    public DIServiceScope CreateScope()
    {
        ThrowIfDisposed();
        var scope = new ScopeState(this, false);
        return new DIServiceScope(
            scope.ServiceProvider,
            scope.Dispose
#if HKW_DI_ASYNC_DISPOSABLE
            , scope.DisposeAsync
#endif
        );
    }

    IServiceScope IServiceScopeFactory.CreateScope() => CreateScope();

    /// <inheritdoc />
    public void Dispose()
    {
        if (Interlocked.Exchange(ref _disposed, 1) != 0)
            return;
        _rootScope.Dispose();
    }

#if HKW_DI_ASYNC_DISPOSABLE
    /// <inheritdoc />
    public ValueTask DisposeAsync()
    {
        if (Interlocked.Exchange(ref _disposed, 1) != 0)
            return default;
        return _rootScope.DisposeAsync();
    }
#endif

    /// <inheritdoc />
    public bool IsService(Type serviceType)
    {
        if (serviceType is null)
            throw new ArgumentNullException(nameof(serviceType));
        return IsBuiltInService(serviceType)
            || IsEnumerable(serviceType)
            || _registrations.ContainsKey(serviceType);
    }

    private object? GetService(Type serviceType, ScopeState scope)
    {
        ThrowIfDisposed();
        scope.ThrowIfDisposed();
        if (serviceType == typeof(IServiceProvider))
            return scope.ServiceProvider;
        if (serviceType == typeof(IServiceScopeFactory))
            return this;
        if (serviceType == typeof(IServiceProviderIsService))
            return this;
        if (_serviceAccessors.TryGetValue(serviceType, out var accessor))
            return accessor(scope);
        if (IsEnumerable(serviceType))
        {
            var elementType = serviceType.GetGenericArguments()[0];
            return _enumerableAccessors.GetOrAdd(elementType, CreateEnumerableAccessor)(scope);
        }
        return null;
    }

    private Func<ScopeState, object?> CreateEnumerableAccessor(Type elementType)
    {
        if (_registrations.TryGetValue(elementType, out var registrations) is false)
            return _ => Array.CreateInstance(elementType, 0);

        return scope =>
        {
            var services = Array.CreateInstance(elementType, registrations.Length);
            for (var index = 0; index < registrations.Length; index++)
                services.SetValue(ResolveRegistration(registrations[index], scope), index);
            return services;
        };
    }

    private object? ResolveRegistration(Registration registration, ScopeState scope)
    {
        ThrowIfDisposed();
        scope.ThrowIfDisposed();
        ValidateResolution(registration, scope);
        return registration.Lifetime switch
        {
            ServiceLifetime.Singleton => registration.GetOrCreateSingleton(
                _rootScope,
                () => CreateService(registration, _rootScope)
            ),
            ServiceLifetime.Scoped => scope.GetOrCreateScoped(
                registration,
                () => CreateService(registration, scope)
            ),
            _ => scope.CaptureDisposable(CreateService(registration, scope)),
        };
    }

    private object? CreateService(Registration registration, ScopeState scope)
    {
        using var resolution = EnterResolution(
            registration.Id,
            registration.ServiceType,
            registration.Lifetime
        );
        return registration.Factory(scope.ServiceProvider);
    }

    private void ValidateResolution(Registration registration, ScopeState scope)
    {
        if (_options.ValidateScopes is false || registration.Lifetime != ServiceLifetime.Scoped)
            return;

        for (var frame = _currentResolution.Value; frame != null; frame = frame.Parent)
        {
            if (
                ReferenceEquals(frame.Provider, this)
                && frame.Lifetime == ServiceLifetime.Singleton
            )
            {
                throw new InvalidOperationException(
                    $"Cannot consume scoped service '{registration.ServiceType}' from singleton '{frame.ServiceType}'."
                );
            }
        }

        if (scope.IsRoot)
        {
            throw new InvalidOperationException(
                $"Cannot resolve scoped service '{registration.ServiceType}' from root provider."
            );
        }
    }

    private void ValidateOnBuild(IEnumerable<DIServiceRegistrationMetadata> metadata)
    {
        var registrations = new Dictionary<Type, List<DIServiceRegistrationMetadata>>();
        foreach (var registration in metadata)
        {
            if (registrations.TryGetValue(registration.ServiceType, out var services) is false)
            {
                services = new List<DIServiceRegistrationMetadata>();
                registrations.Add(registration.ServiceType, services);
            }
            services.Add(registration);
        }

        List<Exception>? exceptions = null;
        foreach (var services in registrations.Values)
        {
            foreach (var registration in services)
            {
                try
                {
                    ValidateMetadata(
                        registration,
                        registrations,
                        new List<DIServiceRegistrationMetadata>(),
                        registration.Lifetime == ServiceLifetime.Singleton ? registration : null
                    );
                }
                catch (Exception exception)
                {
                    (exceptions ??= new List<Exception>()).Add(
                        new InvalidOperationException(
                            $"Error while validating service '{registration.ServiceType}': {exception.Message}",
                            exception
                        )
                    );
                }
            }
        }

        if (exceptions != null)
            throw new AggregateException(
                "Some services are not able to be constructed",
                exceptions
            );
    }

    private void ValidateMetadata(
        DIServiceRegistrationMetadata registration,
        Dictionary<Type, List<DIServiceRegistrationMetadata>> registrations,
        List<DIServiceRegistrationMetadata> path,
        DIServiceRegistrationMetadata? singleton
    )
    {
        if (path.Contains(registration))
        {
            var cycle = path.SkipWhile(item => !ReferenceEquals(item, registration))
                .Select(item => item.ServiceType)
                .Concat(new[] { registration.ServiceType });
            throw new InvalidOperationException(
                $"A circular dependency was detected: {string.Join(" -> ", cycle)}"
            );
        }

        if (
            _options.ValidateScopes
            && singleton != null
            && registration.Lifetime == ServiceLifetime.Scoped
        )
        {
            throw new InvalidOperationException(
                $"Cannot consume scoped service '{registration.ServiceType}' from singleton '{singleton.ServiceType}'."
            );
        }

        path.Add(registration);
        foreach (var dependency in registration.Dependencies)
        {
            if (IsBuiltInService(dependency.ServiceType))
                continue;
            if (!registrations.TryGetValue(dependency.ServiceType, out var candidates))
            {
                if (dependency.IsEnumerable is false 
                    && _registrations.ContainsKey(dependency.ServiceType) is false)
                {
                    throw new InvalidOperationException(
                        $"No service for type '{dependency.ServiceType}' has been registered."
                    );
                }
                continue;
            }

            if (dependency.IsEnumerable)
            {
                foreach (var candidate in candidates)
                    ValidateMetadata(candidate, registrations, path, singleton);
            }
            else
            {
                ValidateMetadata(candidates[candidates.Count - 1], registrations, path, singleton);
            }
        }
        path.RemoveAt(path.Count - 1);
    }

    private static bool IsBuiltInService(Type serviceType) =>
        serviceType == typeof(IServiceProvider)
        || serviceType == typeof(IServiceScopeFactory)
        || serviceType == typeof(IServiceProviderIsService);

    private static bool IsEnumerable(Type serviceType) =>
        serviceType.IsGenericType
        && serviceType.ContainsGenericParameters is false
        && serviceType.GetGenericTypeDefinition() == typeof(IEnumerable<>);

    private void ThrowIfDisposed()
    {
        if (Volatile.Read(ref _disposed) != 0)
            throw new ObjectDisposedException(nameof(DIServiceProvider));
    }

    private IDisposable EnterResolution(
        int registrationId,
        Type serviceType,
        ServiceLifetime lifetime
    )
    {
        var current = _currentResolution.Value;
        for (var frame = current; frame != null; frame = frame.Parent)
        {
            if (ReferenceEquals(frame.Provider, this) && frame.RegistrationId == registrationId)
                throw CreateCircularDependencyException(current, serviceType);
        }

        _currentResolution.Value = new ResolutionFrame(
            this,
            registrationId,
            serviceType,
            lifetime,
            current
        );
        return new ResolutionCookie(current);
    }

    private static InvalidOperationException CreateCircularDependencyException(
        ResolutionFrame? current,
        Type repeatedType
    )
    {
        var types = new List<Type>();
        for (var frame = current; frame != null; frame = frame.Parent)
            types.Add(frame.ServiceType);
        types.Reverse();
        types.Add(repeatedType);
        return new InvalidOperationException(
            $"A circular dependency was detected: {string.Join(" -> ", types)}"
        );
    }

    private sealed class ScopeState : IDisposable
#if HKW_DI_ASYNC_DISPOSABLE
        , IAsyncDisposable
#endif
    {
        private readonly bool _isRoot;
        private readonly Dictionary<int, object?> _services =
            new Dictionary<int, object?>();
        private readonly List<object> _disposables = new List<object>();
        private readonly HashSet<object> _captured =
            new HashSet<object>(ReferenceEqualityComparer.Instance);
        private readonly object _syncRoot = new object();
        private bool _disposed;

        internal ScopeState(DIServiceProvider owner, bool isRoot)
        {
            _isRoot = isRoot;
            ServiceProvider = isRoot
                ? (IServiceProvider)owner
                : new ScopedServiceProvider(owner, this);
        }

        internal IServiceProvider ServiceProvider { get; }

        internal bool IsRoot => _isRoot;

        internal object? GetOrCreateScoped(Registration registration, Func<object?> factory)
        {
            lock (_syncRoot)
            {
                ThrowIfDisposedCore();
                if (_services.TryGetValue(registration.Id, out var existing))
                    return existing;

                var service = factory();
                CaptureDisposable(service);
                _services.Add(registration.Id, service);
                return service;
            }
        }

        internal object? CaptureDisposable(object? service)
        {
#if HKW_DI_ASYNC_DISPOSABLE
            if (service is not IDisposable && service is not IAsyncDisposable)
#else
            if (service is not IDisposable)
#endif
                return service;

            lock (_syncRoot)
            {
                if (_disposed is false)
                {
                    if (_captured.Add(service))
                        _disposables.Add(service);
                    return service;
                }
            }

            DisposeRejectedService(service);
            throw CreateDisposedException();
        }

        internal void ThrowIfDisposed()
        {
            lock (_syncRoot)
                ThrowIfDisposedCore();
        }

        public void Dispose()
        {
            var disposables = BeginDispose();
            if (disposables is null)
                return;

            List<Exception>? exceptions = null;
            for (var index = disposables.Count - 1; index >= 0; index--)
            {
                try
                {
                    if (disposables[index] is IDisposable disposable)
                    {
                        disposable.Dispose();
                    }
#if HKW_DI_ASYNC_DISPOSABLE
                    else
                    {
#pragma warning disable S3877
                        throw new InvalidOperationException(
                            $"'{disposables[index].GetType()}' only implements IAsyncDisposable. Use DisposeAsync to dispose the service provider."
                        );
#pragma warning restore S3877
                    }
#endif
                }
                catch (Exception exception)
                {
                    (exceptions ??= new List<Exception>()).Add(exception);
                }
            }
            ThrowDisposalExceptions(exceptions);
        }

#if HKW_DI_ASYNC_DISPOSABLE
        public async ValueTask DisposeAsync()
        {
            var disposables = BeginDispose();
            if (disposables is null)
                return;

            List<Exception>? exceptions = null;
            for (var index = disposables.Count - 1; index >= 0; index--)
            {
                try
                {
                    if (disposables[index] is IAsyncDisposable asyncDisposable)
                        await asyncDisposable.DisposeAsync().ConfigureAwait(false);
                    else if (disposables[index] is IDisposable disposable)
                        disposable.Dispose();
                }
                catch (Exception exception)
                {
                    (exceptions ??= new List<Exception>()).Add(exception);
                }
            }
            ThrowDisposalExceptions(exceptions);
        }
#endif

        private List<object>? BeginDispose()
        {
            lock (_syncRoot)
            {
                if (_disposed)
                    return null;
                _disposed = true;
                var disposables = new List<object>(_disposables);
                _disposables.Clear();
                _captured.Clear();
                _services.Clear();
                return disposables;
            }
        }

        private void ThrowIfDisposedCore()
        {
            if (_disposed)
                throw CreateDisposedException();
        }

        private ObjectDisposedException CreateDisposedException() =>
            new ObjectDisposedException(_isRoot ? nameof(DIServiceProvider) : "IServiceScope");

        private static void ThrowDisposalExceptions(List<Exception>? exceptions)
        {
            if (exceptions is null)
                return;
            if (exceptions.Count == 1)
                ExceptionDispatchInfo.Capture(exceptions[0]).Throw();
            throw new AggregateException(exceptions);
        }

        private static void DisposeRejectedService(object service)
        {
            if (service is IDisposable disposable)
                disposable.Dispose();
#if HKW_DI_ASYNC_DISPOSABLE
            else if (service is IAsyncDisposable asyncDisposable)
                asyncDisposable.DisposeAsync().AsTask().GetAwaiter().GetResult();
#endif
        }
    }

    private sealed class ScopedServiceProvider : IServiceProvider
    {
        private readonly DIServiceProvider _provider;
        private readonly ScopeState _scope;

        internal ScopedServiceProvider(DIServiceProvider provider, ScopeState scope)
        {
            _provider = provider;
            _scope = scope;
        }

        public object? GetService(Type serviceType) => _provider.GetService(serviceType, _scope);
    }

    private sealed class Registration
    {
        private readonly object _syncRoot = new object();
        private bool _singletonResolved;
        private object? _singleton;

        internal Registration(
            int id,
            Type serviceType,
            ServiceLifetime lifetime,
            Func<IServiceProvider, object> factory
        )
        {
            Id = id;
            ServiceType = serviceType;
            Lifetime = lifetime;
            Factory = factory;
        }

        internal int Id { get; }
        internal Type ServiceType { get; }
        internal ServiceLifetime Lifetime { get; }
        internal Func<IServiceProvider, object> Factory { get; }

        internal object? GetOrCreateSingleton(ScopeState rootScope, Func<object?> create)
        {
            lock (_syncRoot)
            {
                if (_singletonResolved)
                    return _singleton;
                var service = create();
                rootScope.CaptureDisposable(service);
                _singleton = service;
                _singletonResolved = true;
                return service;
            }
        }
    }

    private sealed class ReferenceEqualityComparer : IEqualityComparer<object>
    {
        internal static readonly ReferenceEqualityComparer Instance =
            new ReferenceEqualityComparer();

        public new bool Equals(object? x, object? y) => ReferenceEquals(x, y);

        public int GetHashCode(object obj) => RuntimeHelpers.GetHashCode(obj);
    }

    private sealed class ResolutionFrame
    {
        internal ResolutionFrame(
            DIServiceProvider provider,
            int registrationId,
            Type serviceType,
            ServiceLifetime lifetime,
            ResolutionFrame? parent
        )
        {
            Provider = provider;
            RegistrationId = registrationId;
            ServiceType = serviceType;
            Lifetime = lifetime;
            Parent = parent;
        }

        public DIServiceProvider Provider { get; }
        public int RegistrationId { get; }
        public Type ServiceType { get; }
        public ServiceLifetime Lifetime { get; }
        public ResolutionFrame? Parent { get; }
    }

    private sealed class ResolutionCookie : IDisposable
    {
        private readonly ResolutionFrame? _previous;

        internal ResolutionCookie(ResolutionFrame? previous)
        {
            _previous = previous;
        }

        public void Dispose() => _currentResolution.Value = _previous;
    }
}

/// <summary>由 <see cref="DIServiceProvider"/> 创建的服务作用域
/// </summary>
public sealed class DIServiceScope : IServiceScope
#if HKW_DI_ASYNC_DISPOSABLE
    , IAsyncDisposable
#endif
{
    private readonly Action _dispose;
#if HKW_DI_ASYNC_DISPOSABLE
    private readonly Func<ValueTask> _disposeAsync;
#endif

    internal DIServiceScope(
        IServiceProvider serviceProvider,
        Action dispose
#if HKW_DI_ASYNC_DISPOSABLE
        , Func<ValueTask> disposeAsync
#endif
    )
    {
        ServiceProvider = serviceProvider;
        _dispose = dispose;
#if HKW_DI_ASYNC_DISPOSABLE
        _disposeAsync = disposeAsync;
#endif
    }

    /// <inheritdoc />
    public IServiceProvider ServiceProvider { get; }

    /// <inheritdoc />
    public void Dispose() => _dispose();

#if HKW_DI_ASYNC_DISPOSABLE
    /// <inheritdoc />
    public ValueTask DisposeAsync() => _disposeAsync();
#endif
    }
}
