// <auto-generated/>
#nullable enable

using System;
using System.Collections.Generic;
using System.ComponentModel;
using Microsoft.Extensions.DependencyInjection;

namespace HKW.MVVM.SourceGenerator
{
/// <summary>
/// 配置轻量 <see cref="DIServiceProvider"/> 的验证行为
/// </summary>
public sealed class ServiceProviderOptions
{
    /// <summary>
    /// 获取或设置是否验证作用域服务的解析位置
    /// </summary>
    public bool ValidateScopes { get; set; }

    /// <summary>
    /// 获取或设置是否在构建 Provider 时验证已知依赖图
    /// </summary>
    public bool ValidateOnBuild { get; set; }
}

/// <summary>
/// 供依赖注入源生成代码描述注册依赖
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed class DIServiceRegistrationMetadata
{
    /// <summary>
    /// 初始化注册元数据
    /// </summary>
    public DIServiceRegistrationMetadata(
        Type serviceType,
        ServiceLifetime lifetime,
        DIServiceDependencyMetadata[] dependencies,
        bool dependenciesUnknown = false
    )
    {
        ServiceType = serviceType ?? throw new ArgumentNullException(nameof(serviceType));
        Lifetime = lifetime;
        Dependencies = dependencies ?? throw new ArgumentNullException(nameof(dependencies));
        DependenciesUnknown = dependenciesUnknown;
    }

    /// <summary>
    /// 获取服务类型
    /// </summary>
    public Type ServiceType { get; }

    /// <summary>
    /// 获取服务生命周期
    /// </summary>
    public ServiceLifetime Lifetime { get; }

    /// <summary>
    /// 获取静态可知的依赖
    /// </summary>
    public IReadOnlyList<DIServiceDependencyMetadata> Dependencies { get; }

    /// <summary>
    /// 获取依赖是否包含无法静态分析的部分
    /// </summary>
    public bool DependenciesUnknown { get; }
}

/// <summary>
/// 供依赖注入源生成代码描述单个依赖
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public sealed class DIServiceDependencyMetadata
{
    /// <summary>
    /// 初始化依赖元数据
    /// </summary>
    public DIServiceDependencyMetadata(Type serviceType, bool isEnumerable = false)
    {
        ServiceType = serviceType ?? throw new ArgumentNullException(nameof(serviceType));
        IsEnumerable = isEnumerable;
    }

    /// <summary>
    /// 获取依赖服务类型
    /// </summary>
    public Type ServiceType { get; }

    /// <summary>
    /// 获取依赖是否按集合解析
    /// </summary>
    public bool IsEnumerable { get; }
}

/// <summary>
/// 供生成的 DI 配置公开轻量服务提供程序工厂。
/// </summary>
[EditorBrowsable(EditorBrowsableState.Never)]
public interface IDIGeneratedServiceProviderFactory
{
    /// <summary>创建轻量服务提供程序。</summary>
    DIServiceProvider BuildServiceProvider();

    /// <summary>使用指定验证选项创建轻量服务提供程序。</summary>
    DIServiceProvider BuildServiceProvider(ServiceProviderOptions options);
}

/// <summary>
/// 为通过 <see cref="DIConfigurationBase"/> 引用访问的生成配置提供兼容入口。
/// </summary>
public static class DIConfigurationBaseExtensions
{
    /// <summary>创建由源生成器实现的轻量服务提供程序。</summary>
    public static DIServiceProvider BuildServiceProvider(this DIConfigurationBase configuration)
    {
        if (configuration == null)
            throw new ArgumentNullException(nameof(configuration));
        if (configuration is IDIGeneratedServiceProviderFactory factory)
            return factory.BuildServiceProvider();
        throw new InvalidOperationException(
            "The dependency injection source generator did not generate a service provider for this configuration."
        );
    }

    /// <summary>使用指定验证选项创建源生成的轻量服务提供程序。</summary>
    public static DIServiceProvider BuildServiceProvider(
        this DIConfigurationBase configuration,
        ServiceProviderOptions options
    )
    {
        if (configuration == null)
            throw new ArgumentNullException(nameof(configuration));
        if (options == null)
            throw new ArgumentNullException(nameof(options));
        if (configuration is IDIGeneratedServiceProviderFactory factory)
            return factory.BuildServiceProvider(options);
        throw new InvalidOperationException(
            "The dependency injection source generator did not generate a service provider for this configuration."
        );
    }
}
}
