using System.CodeDom.Compiler;
using System.Text;
using HKW.SourceGeneratorUtils;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace HKW.MVVM.SourceGenerator;

internal class ClassSourceWriter
{
    public static void Execute(ClassInfo classInfo)
    {
        var w = new ClassSourceWriter(classInfo);
        w.Write();
    }

    public static string FirstClassFullName { get; set; } = string.Empty;

    private readonly ClassInfo _classInfo;
    private readonly IndentedTextWriter _writer;

    public ClassSourceWriter(ClassInfo classInfo)
    {
        _classInfo = classInfo;
        var stringStream = new StringWriter();
        _writer = new IndentedTextWriter(stringStream);
    }

    private void Write()
    {
        _writer.WriteLine("// <auto-generated>");
        _writer.WriteLine("#nullable enable");
        _writer.WriteLine("#pragma warning disable CS1591");
        // 添加全部引用
        _writer.WriteLine(_classInfo.Usings);
        // 添加命名空间
        _writer.WriteLine($"namespace {_classInfo.Namespace}");
        _writer.WriteLine("{");
        _writer.Indent++;
        if (_classInfo.FullTypeName == FirstClassFullName)
        {
            // 添加ReferenceType特性,并引用ReactiveObject
            // 防止编译器优化,如果整个项目中不引用ReactiveUI,则ReactiveUI的Assembly不会被程序集引用,会导致Fody无法正常构建
            _writer.WriteLine(
                "[HKW.MVVM.SourceGenerator.ReferenceType(typeof(HKW.MVVM.SourceGenerator.NotifyPropertyChangeFromAttribute))]"
            );
        }
        // 获取可访问性
        var accessibility = _classInfo.DeclarationSyntax.Modifiers.GetAccessibility();
        _writer.WriteLine(
            $"{accessibility}{(_classInfo.ClassSymbol.IsAbstract ? " abstract" : string.Empty)} partial class {_classInfo.TypeName}"
        );
        // 添加约束列表
        if (_classInfo.DeclarationSyntax.ConstraintClauses.Count > 0)
            _writer.WriteLine($"{_classInfo.DeclarationSyntax.ConstraintClauses}");
        _writer.WriteLine("{");
        _writer.Indent++;

        foreach (var info in _classInfo.Members)
            _writer.WriteInfo(info);
        GenerateReactiveHelper();

        _writer.Indent--;
        _writer.WriteLine();
        _writer.WriteLine("}");
        _writer.Indent--;
        _writer.WriteLine("}");

        GeneratorHelper.ProductionContext.AddSource(
            $"{_classInfo.FullTypeName.ReplaceBraces()}.g.cs",
            ((StringWriter)_writer.InnerWriter).ToString()
        );
    }

    public void GenerateReactiveHelper()
    {
        _writer.WriteLine();
        _writer.WriteLine("/// <inheritdoc/>");
        _writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);
        _writer.WriteLine($"protected sealed partial class {_classInfo.HelperObjectName}");
        _writer.WriteLine("{");
        _writer.Indent++;
        GenerateReactiveHelperCtor();
        _writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);
        _writer.WriteLine(GeneratorHelper.DebuggerBrowsableNeverAttribute);
        _writer.WriteLine($"{_classInfo.FullTypeName} _source;");
        foreach (var info in _classInfo.HelperMembers)
            _writer.WriteInfo(info);

        _writer.Indent--;
        _writer.WriteLine("}");
    }

    private void GenerateReactiveHelperCtor()
    {
        _writer.WriteLine("/// <inheritdoc/>");
        _writer.WriteLine(GeneratorHelper.GeneratedCodeAttribute);

        _writer.WriteLine(
            $"public {_classInfo.HelperObjectName}({_classInfo.FullTypeName} source)"
        );
        _writer.WriteLine("{");
        _writer.Indent++;
        _writer.WriteLine("_source = source;");

        foreach (var member in _classInfo.InitializeMembers)
        {
            _writer.WriteLine(member);
        }

        _writer.Indent--;
        _writer.WriteLine("}");
    }
}
