<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Version>0.1.2</Version>
    <Company>HKW</Company>
    <Authors>HKW</Authors>
    <PackageDescription>An source generator MVVM library, based on CommunityToolkit.Mvvm, using SourceGenerator and Fody for mixed source code generation.</PackageDescription>
    <PackageTags>MVVM;Observable;Fody;SourceGenerator;CommunityToolkit;</PackageTags>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <EnforceExtendedAnalyzerRules>false</EnforceExtendedAnalyzerRules>
    <IsRoslynComponent>true</IsRoslynComponent>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageId>HKW.MVVM.SourceGenerator</PackageId>
    <WeaverDirPath>..\HKW.MVVM.SourceGenerator.Fody\bin\$(Configuration)\</WeaverDirPath>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <PropertyGroup>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <PathMap Condition="'$(SolutionDir)' != ''">$(SolutionDir)=/_/</PathMap>
    <PathMap Condition="'$(SolutionDir)' == ''"
      >$(MSBuildProjectDirectory)=/_/$(AssemblyName)/</PathMap
    >
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.9.0" PrivateAssets="all" />
    <PackageReference
      Include="Microsoft.CodeAnalysis.Analyzers"
      Version="5.9.0"
      PrivateAssets="all"
    />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Fody" Version="6.9.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference
      Include="..\HKW.MVVM.SourceGenerator.Fody\HKW.MVVM.SourceGenerator.Fody.csproj"
      ReferenceOutputAssembly="false"
    />
    <PackageReference Include="FodyPackaging" Version="6.9.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <!-- 必须将dll导入NuGet分析器目录, 否则NuGet无法使用源生成 -->
    <None
      Include="$(OutputPath)\$(AssemblyName).dll"
      Pack="true"
      PackagePath="analyzers/dotnet/cs"
      Visible="false"
    />
  </ItemGroup>
  <ItemGroup>
    <!-- 引用的包 -->
    <PackageReference
      Include="HKW.SourceGeneratorUtils"
      Version="0.1.3"
      PrivateAssets="all"
      GeneratePathProperty="true"
    />
    <!-- 将引用的包dll复制进分析器目录, 否则NuGet无法使用 -->
    <None
      Include="$(PkgHKW_SourceGeneratorUtils)\lib\netstandard2.0\*.dll"
      Pack="true"
      PackagePath="analyzers/dotnet/cs"
      Visible="false"
    >
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <!-- 项目分析器必须引用包, 否则 FileNotFoundException -->
    <Analyzer Include="$(PkgHKW_SourceGeneratorUtils)\lib\netstandard2.0\*.dll" />
  </ItemGroup>
</Project>
